server:
  port: 8080
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
  session:
    timeout: 900

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photography_site
    username: root
    password: password123
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database: mysql
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    session:
      tracking-modes: cookie
